### ISSUE TITLE
root_path and output_dir

### ISSUE THREAD

**Issue by shmookpup** [eatbeanss/CSWin-UNet#1]
这个root_path your DATA_DIR 和output_dir your OUT_DIR分别指代什么呀

**Comment by eatbeanss** [comment]
root_path your DATA_DIR是数据集存放路径，output_dir your OUT_DIR是模型保存路径

**Comment by xiaoze0801** [comment]
为啥我复现一直达不到论文的精度啊，跑好几遍了
